<input type="button" 
  onClick="window.print()" 
  value="print deze pagina"/>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h2>Invoice</h2><h3 class="pull-right">Bestelnummer # [[/factuurnummer\]]</h3>
            </div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    				<strong>Klantinfo:</strong><br>
    					[[/voorletters\]] [[/tussenvoegsels\]] [[/achternaam\]]<br>
    					[[/adres\]]<br>
    					[[/postcode\]] [[/woonplaats\]]<br>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
                    <address>
                        <strong>Besteldatum:</strong><br>
                        [[/factuurdatum\]]<br><br>
                    </address>
                </div>
            </div>
        </div>		
    </div>
       
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Order summary</strong></h3>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td><strong>Artikel</strong></td>
                                    <td class="text-center"><strong>Prijs</strong></td>
                                    <td class="text-center"><strong>Aantal</strong></td>
                                    <td class="text-right"><strong>Totaal</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- foreach ($order->lineItems as $line) or some such thing here -->