<div class="row">
	<div class="col-xs-2"><img class="img-responsive" src="/flowerpower/images/producten/[[/product_image\]]">
	</div>
	<div class="col-xs-4">
		<h4 class="product-name"><strong>[[/artikel\]]</strong></h4><h4></h4>
	</div>
	<div class="col-xs-6">
		<div class="col-xs-6 text-right">
			<h6><strong>[[/prijs\]] <span class="text-muted">x</span></strong></h6>
		</div>
		<div class="col-xs-4">
			<input type="number" name="aantal" class="form-control input-sm" value="[[/aantal\]]">
			<input type="hidden" name="artikelcode" value="[[/artikelcode\]]">
		</div>
		<div class="col-xs-2">
			<a href="http://localhost/flowerpower/winkelwagen/deleteFromCart/[[/artikelcode\]]"><button type="button" class="btn btn-link btn-xs">
				<span class="glyphicon glyphicon-trash"> </span>
			</button></a>
		</div>
	</div>
</div>
<hr>