<div class='col-md-4'>
            			<div class='product-item'>
              				<div class='pi-img-wrapper'>
                				<img src='/flowerpower/images/producten/[[/product_image\]]' class=' col-xs-6 col-md-3'>
              				</div>
              				<h3>
              					<a>[[/artikel\]]</a>
              				</h3>
              				<div class='pi-price'>&euro; [[/prijs\]]</div>
              					<a href='http://localhost/flowerpower/producten/add2cart/[[/artikelcode\]]' class='btn add2cart'>Add to cart</a>
             				<div class='sticker'></div>
            			 </div>
        				</div>