<div class="container">
	<h1>Contact pagina</h1>
</div>
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="row">
			<div class="media">

			  <div class="col-xs-6 col-md-3">
	    		<a href="#" class="thumbnail">
			      <img class="media-object contact-img" src="images/540089.jpg" alt="Drachten">
			    </a>
			  </div>
			  <div class="media-body">
			    <h3 class="media-heading">Drachten</h3>
			    <ul>
			    	<li><tr><td>FlowerPower Blom</td></tr></li>
			    	<li><tr><td>Noorderbuurt 31</td></tr></li>
			    	<li><tr><td>9203AL Drachten</td></tr></li>
			    	<li><tr><td>0512883923</td></tr></li>

			    </ul>
				
			  </div>
			</div>
		</div>

		<div class="row">
			<div class="media">

			  <div class="col-xs-6 col-md-3">
	    		<a href="#" class="thumbnail">
			      <img class="media-object contact-img" src="images/540089.jpg" alt="Drachten">
			    </a>
			  </div>
			  <div class="media-body">
			    <h3 class="media-heading">Drachten</h3>
			    <ul>
			    	<li><tr><td>FlowerPower Blom</td></tr></li>
			    	<li><tr><td>Noorderbuurt 31</td></tr></li>
			    	<li><tr><td>9203AL Drachten</td></tr></li>
			    	<li><tr><td>0512883923</td></tr></li>

			    </ul>
				
			  </div>
			</div>
		</div>

		<div class="row">
			<div class="media">

			  <div class="col-xs-6 col-md-3">
	    		<a href="#" class="thumbnail">
			      <img class="media-object contact-img" src="images/540089.jpg" alt="Drachten">
			    </a>
			  </div>
			  <div class="media-body">
			    <h3 class="media-heading">Drachten</h3>
			    <ul>
			    	<li><tr><td>FlowerPower Blom</td></tr></li>
			    	<li><tr><td>Noorderbuurt 31</td></tr></li>
			    	<li><tr><td>9203AL Drachten</td></tr></li>
			    	<li><tr><td>0512883923</td></tr></li>

			    </ul>
				
			  </div>
			</div>
		</div>

		<div class="row">
			<div class="media">

			  <div class="col-xs-6 col-md-3">
	    		<a href="#" class="thumbnail">
			      <img class="media-object contact-img" src="images/540089.jpg" alt="Drachten">
			    </a>
			  </div>
			  <div class="media-body">
			    <h3 class="media-heading">Drachten</h3>
			    <ul>
			    	<li><tr><td>FlowerPower Blom</td></tr></li>
			    	<li><tr><td>Noorderbuurt 31</td></tr></li>
			    	<li><tr><td>9203AL Drachten</td></tr></li>
			    	<li><tr><td>0512883923</td></tr></li>

			    </ul>
				
			  </div>
			</div>
		</div>

		
	
	</div>
</div>
