<div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      
        <section class="section-white">
          <div class="container">

            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <img class="goodSize" src="images/winkel.jpg" alt="...">
                  <div class="carousel-caption">
                    <h2></h2>
                  </div>
                </div>
                <div class="item">
                  <img class="goodSize" src="images/boeket.jpg" alt="...">
                  <div class="carousel-caption">
                    <h2></h2>
                  </div>
                </div>
                <div class="item">
                  <img src="http://placehold.it/800x400" alt="...">
                  <div class="carousel-caption">
                    <h2></h2>
                  </div>
                </div>
              </div>

              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
              </a>
            </div>
              <h2>Dit is de hoofdpagina van winkelketen FlowerPower, al bloemist since 1999.
              Op deze site kunt u al onze aanbiedingen en vestigingen vinden, tevens is het mogelijk om uw boeketen via onze site te bestellen.</h2>
          </div>
    </section>

    </div> <!-- /container -->