<form class="form-horizontal" method="post">
<fieldset>

<!-- Form Name -->
<legend class="text-center">Wijzig mijn gegevens</legend>

  <?php getKlantGegevens(); ?>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="signup"></label>
  <div class="col-md-4">
    <button id="update" name="update" class="btn btn-success" type="submit">Update</button>
  </div>
</div>

</fieldset>
</form>
