
	<div class="row">
		<div class="col-xs-8">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-6">
								<h5><span class="glyphicon glyphicon-shopping-cart"></span> Winkelwagen</h5>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
				<form method="post">
					<?php getCartList(); ?>
					
					<div class="row">
						<div class="text-center">
							<div class="col-xs-9">
								<h6 class="text-right">Producten toegevoegd?</h6>
							</div>
							<div class="col-xs-3">
								<button id="updateA" type="button" class="btn btn-default btn-sm btn-block">
									Update winkelwagen
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
				<div class="row">
							<div class="col-xs-3">Afhalen Bij
								<select name="filiaal" class="selectpicker" required="">
									<option value="">Kies Winkel</option>
									<option value="Sneek">Sneek</option>
									<option value="Heerenveen">Heerenveen</option>
									<option value="Leeuwarden">Leeuwarden</option>
									<option value="Dokkum">Dokkum</option>
									<option value="Drachten">Drachten</option>
								</select>
							</div>
						</div>
					<div class="row text-center">
						<div class="col-xs-9">
							<h4 class="text-right">Totaal &euro; <?= getTotaalPrijs(); ?><strong></strong></h4>
						</div>

						<div class="col-xs-3">
							<button name="bestel" type="submit" class="btn btn-success btn-block">
								Bestel
							</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>